In [1]:
import pandas as pd

In [3]:
df1=pd.read_csv('changeover_cost.csv')
df2=pd.read_csv('changeover_days.csv')
df3=pd.read_csv('delivery_cost.csv')
df4=pd.read_csv('demand_price.csv')
df5=pd.read_csv('fixed_cost.csv')
df6=pd.read_csv('forecast_ideal.csv')
df7=pd.read_csv('ideal_manufacture_sequence.csv')
df8=pd.read_csv('ideal_shipping_region.csv')
df9=pd.read_csv('production_capacity.csv')
df10=pd.read_csv('production_cost.csv')

In [4]:
df1

  Plant  Line      Cost
0     A     1  33536.00
1     A     2  15947.00
2     B     1  13333.00
3     B     2  13333.00
4     B     3  13333.00
5     C     1  54353.39

In [5]:
df2

     From   To  Days
0      P1   P1     0
1      P2   P1     1
2      P3   P1     1
3      P4   P1     1
4      P5   P1     1
5      P6   P1     1
6      P7   P1     1
7      P8   P1     1
8      P9   P1     1
9     P10   P1     1
10    P11   P1     1
11    P12   P1     1
12    P13   P1     2
13    P14   P1     2
14    P15   P1     2
15    P16   P1     2
16    P17   P1     2
17    P18   P1     2
18    P19   P1     2
19    P20   P1     2
20    P21   P1     2
21    P22   P1     2
22    P23   P1     2
23    P24   P1     2
24    P25   P1     2
25    P26   P1     2
26    P27   P1     2
27    P28   P1     2
28    P29   P1     2
29    P30   P1     2
...   ...  ...   ...
6531  P52  P81    10
6532  P53  P81    10
6533  P54  P81    10
6534  P55  P81     2
6535  P56  P81     2
6536  P57  P81     2
6537  P58  P81     2
6538  P59  P81     2
6539  P60  P81     2
6540  P61  P81     2
6541  P62  P81     2
6542  P63  P81     2
6543  P64  P81     2
6544  P65  P81     2
6545  P66  P81     2
6546  P67  P81     2
6547  P68  P81     2
6548  P69  P81     2
6549  P70  P81     2
6550  P71  P81     2
6551  P72  P81     2
6552  P73  P81     2
6553  P74  P81     2
6554  P75  P81     2
6555  P76  P81     2
6556  P77  P81     2
6557  P78  P81     2
6558  P79  P81     2
6559  P80  P81     2
6560  P81  P81     0

[6561 rows x 3 columns]

In [6]:
df3

   Plant Region  Delivery_cost
0      A     R1      85.541475
1      A     R2     223.934332
2      A     R3      34.648618
3      A     R4      32.059332
4      A     R5     121.255760
5      A     R6      34.648618
6      A     R7     139.112903
7      A     R8     114.112903
8      A     R9     130.184332
9      A    R10     112.327189
10     A    R11     148.041475
11     A    R12      34.648618
12     A    R13      34.648618
13     A    R14     121.255760
14     A    R15      31.970046
15     A    R16     165.898618
16     A    R17      81.077189
17     A    R18     107.862903
18     B     R1      63.000000
19     B     R2     287.000000
20     B     R3      90.000000
21     B     R4      41.000000
22     B     R5     144.000000
23     B     R6      59.000000
24     B     R7     153.000000
25     B     R8     242.000000
26     B     R9     130.000000
27     B    R10     113.000000
28     B    R11     233.000000
29     B    R12      54.000000
30     B    R13      63.000000
31     B    R14     126.000000
32     B    R15      41.000000
33     B    R16     287.000000
34     B    R17     144.000000
35     B    R18     117.000000
36     C     R1     277.030075
37     C     R2      44.999574
38     C     R3     277.030075
39     C     R4     200.000000
40     C     R5      44.999574
41     C     R6     277.030075
42     C     R7      44.999574
43     C     R8     170.235257
44     C     R9      44.999574
45     C    R10      44.999574
46     C    R11     213.722138
47     C    R12     200.000000
48     C    R13     200.000000
49     C    R14      45.000000
50     C    R15     200.000000
51     C    R16      75.822474
52     C    R17     228.305118
53     C    R18     273.880474

In [7]:
df4

     Product_ID Region  Demand_price
0            P1     R1      0.000000
1            P2     R1      0.000000
2            P3     R1      0.000000
3            P4     R1      0.000000
4            P5     R1      0.000000
5            P6     R1      0.000000
6            P7     R1      0.000000
7            P8     R1      0.000000
8            P9     R1      0.000000
9           P10     R1      0.000000
10          P11     R1      0.000000
11          P12     R1      0.000000
12          P13     R1      0.000000
13          P14     R1      0.000000
14          P15     R1      0.000000
15          P16     R1      0.000000
16          P17     R1      0.000000
17          P18     R1      0.000000
18          P19     R1      0.000000
19          P20     R1      0.000000
20          P21     R1      0.000000
21          P22     R1      0.000000
22          P23     R1      0.000000
23          P24     R1      0.000000
24          P25     R1      0.000000
25          P26     R1      0.000000
26          P27     R1      0.000000
27          P28     R1      0.000000
28          P29     R1      0.000000
29          P30     R1      0.000000
...         ...    ...           ...
1428        P52    R18      0.000000
1429        P53    R18      0.000000
1430        P54    R18      0.000000
1431        P55    R18      0.000000
1432        P56    R18      0.000000
1433        P57    R18   2516.450178
1434        P58    R18   2648.957373
1435        P59    R18      0.000000
1436        P60    R18   2473.681590
1437        P61    R18   2570.128209
1438        P62    R18      0.000000
1439        P63    R18      0.000000
1440        P64    R18   2498.735759
1441        P65    R18      0.000000
1442        P66    R18      0.000000
1443        P67    R18   3123.419698
1444        P68    R18   2974.685427
1445        P69    R18      0.000000
1446        P70    R18      0.000000
1447        P71    R18      0.000000
1448        P72    R18   3123.419698
1449        P73    R18      0.000000
1450        P74    R18   3153.166553
1451        P75    R18   2915.613660
1452        P76    R18      0.000000
1453        P77    R18   4462.028141
1454        P78    R18      0.000000
1455        P79    R18      0.000000
1456        P80    R18   5175.952643
1457        P81    R18      0.000000

[1458 rows x 3 columns]

In [8]:
df5

  Plant  Line      Cost
0     A     1  33536.00
1     A     2  15947.00
2     B     1  13333.00
3     B     2  13333.00
4     B     3  13333.00
5     C     1  54353.39

In [9]:
df6

     Product_ID Region  Month  Demand
0            P1     R1     34    0.00
1            P1     R1     35    0.00
2            P1     R1     36    0.00
3            P1    R10     34    0.00
4            P1    R10     35    0.00
5            P1    R10     36    0.00
6            P1    R11     34    0.00
7            P1    R11     35    0.00
8            P1    R11     36    0.00
9            P1    R12     34    0.00
10           P1    R12     35    0.00
11           P1    R12     36    0.00
12           P1    R13     34    0.00
13           P1    R13     35    0.00
14           P1    R13     36    0.00
15           P1    R14     34    0.00
16           P1    R14     35    0.00
17           P1    R14     36    0.00
18           P1    R15     34    0.00
19           P1    R15     35    0.00
20           P1    R15     36    0.00
21           P1    R16     34    0.00
22           P1    R16     35    0.00
23           P1    R16     36    0.00
24           P1    R17     34    0.00
25           P1    R17     35    0.00
26           P1    R17     36    0.00
27           P1    R18     34    0.00
28           P1    R18     35    0.00
29           P1    R18     36    0.00
...         ...    ...    ...     ...
4344         P9    R17     34    0.00
4345         P9    R17     35    0.00
4346         P9    R17     36    0.00
4347         P9    R18     34   11.70
4348         P9    R18     35   14.41
4349         P9    R18     36   15.05
4350         P9     R2     34    0.00
4351         P9     R2     35    0.00
4352         P9     R2     36    0.00
4353         P9     R3     34   35.10
4354         P9     R3     35  172.92
4355         P9     R3     36  105.35
4356         P9     R4     34    0.00
4357         P9     R4     35    0.00
4358         P9     R4     36    0.00
4359         P9     R5     34  128.70
4360         P9     R5     35  100.87
4361         P9     R5     36  105.35
4362         P9     R6     34    0.00
4363         P9     R6     35    0.00
4364         P9     R6     36    0.00
4365         P9     R7     34    0.00
4366         P9     R7     35    0.00
4367         P9     R7     36    0.00
4368         P9     R8     34    0.00
4369         P9     R8     35    0.00
4370         P9     R8     36   15.05
4371         P9     R9     34  140.40
4372         P9     R9     35   86.46
4373         P9     R9     36   90.30

[4374 rows x 4 columns]

In [10]:
df7

    Plant  Line  Month  Day Product_ID
0       A     1     34    1         P3
1       A     1     34    2         P3
2       A     1     34    3        NaN
3       A     1     34    4         P8
4       A     1     34    5        NaN
5       A     1     34    6        NaN
6       A     1     34    7        P13
7       A     1     34    8        P13
8       A     1     34    9        P13
9       A     1     34   10        P13
10      A     1     34   11        NaN
11      A     1     34   12        NaN
12      A     1     34   13        NaN
13      A     1     34   14        NaN
14      A     1     34   15        NaN
15      A     1     34   16        NaN
16      A     1     34   17        NaN
17      A     1     34   18        NaN
18      A     1     34   19        NaN
19      A     1     34   20        NaN
20      A     1     34   21        P57
21      A     1     34   22        P57
22      A     1     34   23        P57
23      A     1     34   24        P57
24      A     1     34   25        NaN
25      A     1     34   26        NaN
26      A     1     34   27        NaN
27      A     1     34   28        NaN
28      A     1     34   29        P60
29      A     1     34   30        P60
..    ...   ...    ...  ...        ...
510     C     1     36    1        P40
511     C     1     36    2        P40
512     C     1     36    3        P40
513     C     1     36    4        P40
514     C     1     36    5        P40
515     C     1     36    6        P40
516     C     1     36    7        NaN
517     C     1     36    8        P14
518     C     1     36    9        P14
519     C     1     36   10        P14
520     C     1     36   11        P14
521     C     1     36   12        P14
522     C     1     36   13        NaN
523     C     1     36   14        P13
524     C     1     36   15        P13
525     C     1     36   16        P13
526     C     1     36   17        P13
527     C     1     36   18        P13
528     C     1     36   19        P13
529     C     1     36   20        P13
530     C     1     36   21        P13
531     C     1     36   22        P13
532     C     1     36   23        P13
533     C     1     36   24        NaN
534     C     1     36   25        NaN
535     C     1     36   26         P9
536     C     1     36   27         P9
537     C     1     36   28         P9
538     C     1     36   29         P9
539     C     1     36   30         P9

[540 rows x 5 columns]

In [11]:
df8

      Plant Region Product_ID  Month  Shipping_to_region_quantity
0         A     R1         P1     34                          0.0
1         A     R1         P2     34                          0.0
2         A     R1         P3     34                          0.0
3         A     R1         P4     34                          0.0
4         A     R1         P5     34                          0.0
5         A     R1         P6     34                          0.0
6         A     R1         P7     34                          0.0
7         A     R1         P8     34                          0.0
8         A     R1         P9     34                          0.0
9         A     R1        P10     34                          0.0
10        A     R1        P11     34                          0.0
11        A     R1        P12     34                          0.0
12        A     R1        P13     34                          0.0
13        A     R1        P14     34                          0.0
14        A     R1        P15     34                          0.0
15        A     R1        P16     34                          0.0
16        A     R1        P17     34                          0.0
17        A     R1        P18     34                          0.0
18        A     R1        P19     34                          0.0
19        A     R1        P20     34                          0.0
20        A     R1        P21     34                          0.0
21        A     R1        P22     34                          0.0
22        A     R1        P23     34                          0.0
23        A     R1        P24     34                          0.0
24        A     R1        P25     34                          0.0
25        A     R1        P26     34                          0.0
26        A     R1        P27     34                          0.0
27        A     R1        P28     34                          0.0
28        A     R1        P29     34                          0.0
29        A     R1        P30     34                          0.0
...     ...    ...        ...    ...                          ...
13092     C    R18        P52     36                          0.0
13093     C    R18        P53     36                          0.0
13094     C    R18        P54     36                          0.0
13095     C    R18        P55     36                          0.0
13096     C    R18        P56     36                          0.0
13097     C    R18        P57     36                          0.0
13098     C    R18        P58     36                          0.0
13099     C    R18        P59     36                          0.0
13100     C    R18        P60     36                          0.0
13101     C    R18        P61     36                          0.0
13102     C    R18        P62     36                          0.0
13103     C    R18        P63     36                          0.0
13104     C    R18        P64     36                          0.0
13105     C    R18        P65     36                          0.0
13106     C    R18        P66     36                          0.0
13107     C    R18        P67     36                          0.0
13108     C    R18        P68     36                          0.0
13109     C    R18        P69     36                          0.0
13110     C    R18        P70     36                          0.0
13111     C    R18        P71     36                          0.0
13112     C    R18        P72     36                          0.0
13113     C    R18        P73     36                          0.0
13114     C    R18        P74     36                          0.0
13115     C    R18        P75     36                          0.0
13116     C    R18        P76     36                          0.0
13117     C    R18        P77     36                          0.0
13118     C    R18        P78     36                          0.0
13119     C    R18        P79     36                          0.0
13120     C    R18        P80     36                          0.0
13121     C    R18        P81     36                          0.0

[13122 rows x 5 columns]

In [12]:
df9

    Plant  Line Product  Capacity
0       A     1      P1         0
1       A     1      P2         0
2       A     1      P3       210
3       A     1      P4         0
4       A     1      P5       210
5       A     1      P6         0
6       A     1      P7       165
7       A     1      P8       195
8       A     1      P9       200
9       A     1     P10         0
10      A     1     P11         0
11      A     1     P12         0
12      A     1     P13       125
13      A     1     P14         0
14      A     1     P15         0
15      A     1     P16       125
16      A     1     P17         0
17      A     1     P18         0
18      A     1     P19       125
19      A     1     P20         0
20      A     1     P21         0
21      A     1     P22       120
22      A     1     P23         0
23      A     1     P24         0
24      A     1     P25         0
25      A     1     P26         0
26      A     1     P27         0
27      A     1     P28       110
28      A     1     P29         0
29      A     1     P30       120
..    ...   ...     ...       ...
456     C     1     P52         0
457     C     1     P53         0
458     C     1     P54         0
459     C     1     P55         0
460     C     1     P56         0
461     C     1     P57         0
462     C     1     P58         0
463     C     1     P59         0
464     C     1     P60         0
465     C     1     P61         0
466     C     1     P62         0
467     C     1     P63         0
468     C     1     P64         0
469     C     1     P65         0
470     C     1     P66         0
471     C     1     P67         0
472     C     1     P68         0
473     C     1     P69         0
474     C     1     P70         0
475     C     1     P71         0
476     C     1     P72         0
477     C     1     P73         0
478     C     1     P74         0
479     C     1     P75         0
480     C     1     P76         0
481     C     1     P77         0
482     C     1     P78         0
483     C     1     P79         0
484     C     1     P80         0
485     C     1     P81         0

[486 rows x 4 columns]

In [13]:
df10

    Product_ID Plant  Production_cost
0           P1     A             0.00
1           P2     A             0.00
2           P3     A           984.44
3           P4     A             0.00
4           P5     A          1358.41
5           P6     A             0.00
6           P7     A           980.85
7           P8     A           992.19
8           P9     A          1009.49
9          P10     A             0.00
10         P11     A             0.00
11         P12     A             0.00
12         P13     A          1110.78
13         P14     A             0.00
14         P15     A             0.00
15         P16     A          1702.13
16         P17     A             0.00
17         P18     A             0.00
18         P19     A          1217.41
19         P20     A             0.00
20         P21     A             0.00
21         P22     A          1123.83
22         P23     A             0.00
23         P24     A             0.00
24         P25     A             0.00
25         P26     A             0.00
26         P27     A             0.00
27         P28     A          1106.55
28         P29     A             0.00
29         P30     A          1102.20
..         ...   ...              ...
213        P52     C             0.00
214        P53     C             0.00
215        P54     C             0.00
216        P55     C             0.00
217        P56     C             0.00
218        P57     C             0.00
219        P58     C             0.00
220        P59     C             0.00
221        P60     C             0.00
222        P61     C             0.00
223        P62     C             0.00
224        P63     C             0.00
225        P64     C             0.00
226        P65     C             0.00
227        P66     C             0.00
228        P67     C             0.00
229        P68     C             0.00
230        P69     C             0.00
231        P70     C             0.00
232        P71     C             0.00
233        P72     C             0.00
234        P73     C             0.00
235        P74     C             0.00
236        P75     C             0.00
237        P76     C             0.00
238        P77     C             0.00
239        P78     C             0.00
240        P79     C             0.00
241        P80     C             0.00
242        P81     C             0.00

[243 rows x 3 columns]